import { Nav } from '@components/nav'
import { SessionProvider } from '@components/providers'
import { getServerSession } from '@libs/auth'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession()

  return (
    <html lang="en">
      <body className={inter.className}>
        <Nav />
        <SessionProvider session={session}>{children}</SessionProvider>
      </body>
    </html>
  )
}
